# Generated by Django 5.1.2 on 2024-11-20 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredavacIzborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.CharField(choices=[('diplomski_studij', 'Sveučilišni diplomski ili stručni diplomski studij'), ('neki_drugi', 'Neki drugi studij')], help_text='Navedite završen studij', max_length=50)),
                ('diploma_document', models.FileField(blank=True, help_text='Upload your diploma', null=True, upload_to='Diplome/')),
                ('teaching_hours', models.PositiveIntegerField(blank=True, help_text='Broj održanih norma sati u sustavu visokog obrazovanja', null=True)),
                ('crosbi_profile_link', models.URLField(blank=True, help_text='Link to your updated Crosbi profile', null=True)),
                ('number_of_published_papers', models.PositiveIntegerField(default=0, help_text='Broj objavljenih stručnih ili znanstvenih radova')),
                ('papers_documents', models.FileField(blank=True, help_text='Upload your papers (in ZIP format if multiple)', null=True, upload_to='Radovi/')),
                ('patent_document', models.FileField(blank=True, help_text='Upload document of patent proof', null=True, upload_to='Patenti/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredavacReizborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_elected_lecturer', models.BooleanField(default=False, help_text='Jeste li bili izabrani na nastavno mjesto predavača')),
                ('teaching_hours', models.PositiveIntegerField(blank=True, help_text='Broj održanih norma sati nastave', null=True)),
                ('published_works_count', models.PositiveIntegerField(default=0, help_text='Broj objavljenih stručnih, znanstvenih ili umjetničkih radova')),
                ('papers_documents', models.FileField(blank=True, help_text='Upload your papers (in ZIP format if multiple)', null=True, upload_to='Radovi/')),
                ('project_leadership_experience', models.BooleanField(default=False, help_text='Imate li iskustvo vođenja ili suvoditeljstva na projektima?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('prijava_tip', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorStrucnogStudijaIzborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctorate_or_alternative', models.FileField(blank=True, help_text='Upload your doctorate diploma or alternative scientific contribution', null=True, upload_to='Diplome/')),
                ('teaching', models.PositiveIntegerField(blank=True, help_text='Broj održanih norma sati nastaveu prethodnom izbornom razdoblju', null=True)),
                ('reviewed_teaching_material', models.BooleanField(default=False, help_text='Has published reviewed teaching material for the course.')),
                ('mentorship_count', models.PositiveIntegerField(default=0, help_text='Number of mentored final and/or graduate theses.')),
                ('coauthored_papers_with_students', models.PositiveIntegerField(default=0, help_text='Number of co-authored papers with students.')),
                ('presented_papers_count', models.PositiveIntegerField(default=0, help_text='Number of presented papers at conferences.')),
                ('international_papers_count', models.PositiveIntegerField(default=0, help_text='Number of international conference presentations.')),
                ('participated_in_international_mobility', models.BooleanField(default=False, help_text='Has participated in international mobility or professional training.')),
                ('led_international_project', models.BooleanField(default=False, help_text='Has led an international project or significant documented contribution in relevant fields.')),
                ('received_international_award', models.BooleanField(default=False, help_text='Has received an international or notable domestic award for educational, scientific, or artistic contribution.')),
                ('google_scholar_citations', models.PositiveIntegerField(default=0, help_text='Number of new confirmed Google Scholar citations.')),
                ('exhibitions_count', models.PositiveIntegerField(default=0, help_text='Number of organized artistic exhibitions.')),
                ('reviewed_academic_manuals', models.PositiveIntegerField(default=0, help_text='Number of reviewed academic manuals or textbooks.')),
                ('attended_professional_workshops', models.PositiveIntegerField(default=0, help_text='Number of professional workshops attended in the relevant scientific field.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorStrucnogStudijaReizborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_reviewed_teaching_material', models.BooleanField(default=False, help_text='Has published reviewed teaching material for the course.')),
                ('mentorship_theses_count', models.PositiveIntegerField(default=0, help_text='Number of final and/or graduate theses mentored (min. 7).')),
                ('coauthored_papers_with_students_count', models.PositiveIntegerField(default=0, help_text='Number of co-authored papers with students (min. 3).')),
                ('presented_papers_count', models.PositiveIntegerField(default=0, help_text='Total number of presented papers at conferences (min. 4).')),
                ('international_papers_count', models.PositiveIntegerField(default=0, help_text='Number of international conference presentations (min. 2).')),
                ('participated_in_international_mobility', models.BooleanField(default=False, help_text='Has participated in international mobility or professional training.')),
                ('led_international_project', models.BooleanField(default=False, help_text='Has led an international project or documented significant professional contribution in the field.')),
                ('received_award', models.BooleanField(default=False, help_text='Has received an international or significant domestic award.')),
                ('google_scholar_citations', models.PositiveIntegerField(default=0, help_text='New confirmed Google Scholar citations (min. 20).')),
                ('exhibitions_count', models.PositiveIntegerField(default=0, help_text='Number of organized artistic exhibitions (min. 5).')),
                ('reviewed_academic_manuals', models.PositiveIntegerField(default=0, help_text='Number of reviewed academic manuals or involvement in program organization (min. 1).')),
                ('attended_professional_workshops', models.PositiveIntegerField(default=0, help_text='Number of professional workshops attended in the relevant field (min. 5).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorStrucnogStudijaTrajniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_previous_professor_position', models.BooleanField(default=False, help_text='Already held the position of professor in the previous term.')),
                ('teaching_hours_last_term', models.PositiveIntegerField(default=0, help_text='Number of teaching hours completed in the previous term (min. 240).')),
                ('academic_papers_count', models.PositiveIntegerField(default=0, help_text='Number of published academic papers or projects (min. 3).')),
                ('patents_count', models.PositiveIntegerField(default=0, help_text='Number of recognized patents.')),
                ('translations_count', models.PositiveIntegerField(default=0, help_text='For philology: Number of translated works.')),
                ('sports_team_management_count', models.PositiveIntegerField(default=0, help_text='For kinesiology: Number of student teams managed (min. 3).')),
                ('has_reviewed_teaching_material', models.BooleanField(default=False, help_text='Has published reviewed teaching material.')),
                ('mentorship_theses_count', models.PositiveIntegerField(default=0, help_text='Number of mentored final or graduate theses (min. 7).')),
                ('coauthored_papers_with_students_count', models.PositiveIntegerField(default=0, help_text='Number of co-authored papers with students (min. 3).')),
                ('presented_papers_count', models.PositiveIntegerField(default=0, help_text='Total number of papers presented at conferences (min. 4).')),
                ('international_papers_count', models.PositiveIntegerField(default=0, help_text='Number of international conference presentations (min. 2).')),
                ('participated_in_international_mobility', models.BooleanField(default=False, help_text='Participated in international mobility or professional training.')),
                ('led_international_project', models.BooleanField(default=False, help_text='Led an international project or contributed significantly to one.')),
                ('highest_level_works_count', models.PositiveIntegerField(default=0, help_text='Number of high-level works or projects (min. 2).')),
                ('received_award', models.BooleanField(default=False, help_text='Received international or significant domestic award.')),
                ('google_scholar_citations', models.PositiveIntegerField(default=0, help_text='New confirmed citations on Google Scholar (min. 20).')),
                ('exhibitions_count', models.PositiveIntegerField(default=0, help_text='Number of artistic exhibitions attended or organized (min. 5).')),
                ('reviewed_academic_manuals_count', models.PositiveIntegerField(default=0, help_text='Reviewed academic manuals or participated in curriculum innovation (min. 1).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisiPredavacIzborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diploma_document', models.FileField(blank=True, help_text='Upload your diploma', null=True, upload_to='Diplome/')),
                ('teaching_hours', models.PositiveIntegerField(blank=True, help_text='Broj održanih norma sati u sustavu visokog obrazovanja', null=True)),
                ('crosbi_profile_link', models.URLField(blank=True, help_text='Link to your updated Crosbi profile', null=True)),
                ('teaching_material', models.FileField(blank=True, help_text='Upload your teaching material', null=True, upload_to='Nastavni materijali/')),
                ('mentoring', models.FileField(blank=True, help_text="Upload your final assigment's with students in ZIP format", null=True, upload_to='Mentorstva/')),
                ('gatherings', models.BooleanField(default=False, help_text='Jeste li sudjelovali na domaćim ili međunarodnim skupovima?')),
                ('reviewed_scientific_papers', models.FileField(blank=True, help_text='Upload scientific papers that you reviewed in ZIP format', null=True, upload_to='Recenzirani radovi/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisiPredavacReizborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teaching_hours', models.PositiveIntegerField(blank=True, help_text='Broj održanih norma sati nastave', null=True)),
                ('crosbi_profile_link', models.URLField(blank=True, help_text='Link to your updated Crosbi profile', null=True)),
                ('scientific_paper_high_level', models.FileField(blank=True, help_text='Upload your scientific papers (in ZIP format if multiple)', null=True, upload_to='Znanstveni radovi/')),
                ('doctorate_or_alternative', models.FileField(blank=True, help_text='Upload your doctorate diploma or alternative scientific contribution', null=True, upload_to='Diplome/')),
                ('scientific_papers', models.FileField(blank=True, help_text='Upload at least three scientific papers that you wrote in ZIP format', null=True, upload_to='Znanstveni radovi/')),
                ('project_participation', models.FileField(blank=True, help_text='Upload projects that you participated in', null=True, upload_to='Znanstveni radovi/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
